Don't filter ontologies with no domain when not grouping by domain
OBOFoundry/OBOFoundry.github.io pull request #2114
Opened 2022-09-30 04:55 UTC by erik-whiting

With these changes, the homepage will show ontologies that don't have a domain if the "Group by Domain" checkbox is unchecked. I believe this is what the reporter of #2107 wants.

Something to think about: Do you want to put a "No Domain" grouping when looking at ontologies grouped by domain? This will be a little bit more work but if it's something that would be helpful to your users, I'd be happy to take a shot at it.

2022-09-30 11:05 UTC, cthoyt commented
@erik-whiting sorry for the double post, but here I think a curation solution would be better than doing more programming

2022-09-30 11:33 UTC, matentzn commented
@cthoyt - I see it a bit differently. This PR solves a problem we currently have with the code - your are talking about "using the opportunity of this bug to enhance the metadata".. 

Here is my reasoning:

1. @erik-whiting took the time to investigate the code to figure out how to display ontologies in the "no domain" view. It's important that we make such contributions if they correctly address the issue easy to do and not add additional churn by saying: it would be better to solve this other problem (incomplete metadata) instead. @erik-whiting is unlikely to solve the metadata + QC issue now (correct me if I am wrong @erik-whiting).
2. We have no dedicated support for fixing the metadata now, and it can be fixed entirely independently of this PR.
3. Some OBO ontologies are not shown on the frontpage which is bad. 

My suggestion is to merge this PR (Thank you @erik-whiting, again!) and if adding domains for all these ontologies is a concern, make a separate issue about that. Let me know what you think!

2022-09-30 11:37 UTC, cthoyt commented
@matentzn okay yes you have a good point. Sorry, I should have started by saying thank you @erik-whiting for figuring this out! Let's move forwards the way you suggested (though I would ask kindly that Erik put LOTS of code comments explaining what this javascript is doing, and why, before accepting this PR)

2022-09-30 12:01 UTC, matentzn requested changes
Excellent @erik-whiting thank you! Can you add some inline comments just above your changes in the code what their part of the code is doing and why it had to change? That would be fabulous! Thanks @cthoyt for the review :D

2022-09-30 13:28 UTC, erik-whiting commented
> @erik-whiting took the time to investigate the code to figure out how to display ontologies in the "no domain" view

Thanks, but just so you know, you don't have to accept my PR just because I made one. If there's a more preferable solution, I won't be offended if this PR is rejected.

> @erik-whiting is unlikely to solve the metadata + QC issue now

This is true, I wouldn't know where to start

> Can you add some inline comments just above your changes

Yes, I can do this after work today

2022-09-30 14:57 UTC, matentzn commented
> Thanks, but just so you know, you don't have to accept my PR just because I made one. 

Hahha don't worry. It will be accepted because it solves a problem :) we would never accept a PR if we didn't believe that!

2022-10-01 12:16 UTC, matentzn approved these changes

2022-10-01 12:17 UTC, matentzn commented
Thank you @erik-whiting

2022-10-01 12:17 UTC, merged