Create t4fs.md
OBOFoundry/OBOFoundry.github.io pull request #2140
Opened 2022-10-05 10:57 UTC by allysonlister

Added as part of the work for #1520

2022-10-05 15:07 UTC, jamesaoverton commented
The automated checks did not run for my last commit. <https://www.githubstatus.com/> says that "Actions is experiencing degraded performance".

2022-10-05 18:56 UTC, cthoyt commented
needs a `preferredPrefix` and to use an appropriate `domain`

2022-10-05 19:33 UTC, matentzn commented on ontology/t4fs.md
> +domain: information
changed that.

2022-10-05 19:33 UTC, matentzn commented
@allysonlister can you review my changes - they were needed to pass the file!

2022-10-05 19:45 UTC, cthoyt commented
before putting @drosophilic as the contact, would be good to get a confirmation from him that he knows that he is responsible for github inquiries on this

2022-10-05 19:46 UTC, cthoyt commented on ontology/t4fs.md
> +- id: t4fs-community.owl
can you add "title" keys for all of these so we can tell what the difference is between the base ones and the `-community` ones?

2022-10-06 08:55 UTC, matentzn requested changes
- [ ] confirm the two edits performed by me
- [ ] Address @cthoyt suggestions on for better descriptions of release artefacts

2022-10-06 11:17 UTC, allysonlister commented
I have done the first two you requested @matentzn - hopefully it looks OK as the titles look a bit repetitive but I couldn't figure out a way to have one title for all community formats.

I have emailed @drosophilic and am waiting to hear back from him, as it may be best to switch our names, I'll update once I know more. Thanks!

2022-10-07 08:28 UTC, Drosophilic commented
Hello! Apologies for the radio silence, I was snowed under at work. Allyson has done a great deal of work on this and I think it makes perfect sense for @allysonlister to be the OBO contact.

2022-10-10 08:00 UTC, allysonlister commented
Super, thank you! I've updated the contact details to me. Is there anything left to do now, as I believe I've done everything requested?

Thanks very much!

2022-10-10 08:29 UTC, cthoyt approved these changes

2022-10-10 11:33 UTC, matentzn approved these changes

2022-10-10 11:34 UTC, merged