Update operations.yml
OBOFoundry/OBOFoundry.github.io pull request #2349
Opened 2023-04-28 18:07 UTC by LK112019

Could you please add me to the OBO Foundry site?
Thanks so much!

2023-04-28 19:58 UTC, LK112019 reviewed
ORCID ID has been added. Thanks!

2023-04-28 20:27 UTC, LK112019 reviewed
ror# has been added

2023-04-28 20:31 UTC, matentzn requested changes
Thanks 
@LK112019 No need for the empty keys. Not sure if wikidata is required, let's see.

2023-04-28 20:31 UTC, matentzn commented on _data/operations.yml
> +  link:
```suggestion
```

2023-04-28 20:31 UTC, matentzn commented on _data/operations.yml
> +  wikidata:
```suggestion
```

2023-04-29 22:17 UTC, cthoyt commented
Photo is required. I made a wikidata for you, see #2353

2023-04-30 15:19 UTC, cthoyt commented on _data/operations.yml
> +  wikidata:
```suggestion
  wikidata: Q118105252
```

2023-05-02 07:45 UTC, matentzn approved these changes

2023-05-02 07:58 UTC, merged