Update cdno.md
OBOFoundry/OBOFoundry.github.io pull request #2557
Opened 2024-03-27 23:18 UTC by LilyAndres

Update contact email and I recently moved the repo to a new organisation so the path has changed for the repo, as well as the publication.

2024-04-01 10:25 UTC, LilyAndres commented
I have followed the How do I edit the metadata for my ontology?
 [link](http://obofoundry.org/faq/how-do-i-edit-metadata.html#:~:text=Editing%20metadata%3A%20first%20create%20a,based%20editor%20for%20their%20metadata.&text=You%20don't%20need%20to,big%20green%20button%20to%20fork!) I have checked the changes and everything looks ok. I think I might need help to merge this pull request @cmungall I hope you can help me, apologies for the inconvenience.

2024-04-01 15:27 UTC, cmungall approved these changes

2024-04-01 20:46 UTC, deepakunni3 requested changes

2024-04-02 05:05 UTC, LilyAndres commented on ontology/cdno.md
>  repository: https://github.com/Southern-Cross-Plant-Science/cdno
Thanks for the changes @deepakunni3 they are correct, thanks for your help.

2024-04-02 06:38 UTC, deepakunni3 approved these changes

2024-04-02 06:39 UTC, merged