Update RoleNORManager.md
OBOFoundry/OBOFoundry.github.io pull request #2631
Opened 2024-08-10 06:20 UTC by matentzn

Replaces #2571

2024-08-11 20:22 UTC, nlharris requested changes
Requesting minor edits

2024-08-11 20:22 UTC, nlharris commented on docs/roles/RoleNORManager.md
> +The OBO Duty Rotation Table is a Google Doc available [here](https://docs.google.com/spreadsheets/d/19GrEWVnpxjnrig0iYUOiUvsZ0JDbprMh1USnRb-SXtg/edit).
mention that it is editable by everyone on the OBO Ops committee?

2024-08-11 20:22 UTC, nlharris commented on docs/roles/RoleNORManager.md
> +When a new member is added to OBO Foundry, the OBO NOR reviewer should add their name to this table. Likewise, former members should be removed from the table. The soure of truth for OBO Foundry memb
```suggestion
When a new member is added to OBO Foundry, the OBO NOR reviewer should add their name to this table. Likewise, former members should be removed from the table. The list of current OBO Foundry members is maintained in the file [operations.yml](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_data/operations.yml).
```

2024-08-11 20:22 UTC, nlharris commented on docs/roles/RoleNORManager.md
> +In addition, when a new ontology has been added, it should be documented to the 'Ontology Review Rotation' sheet in the same document.
```suggestion
In addition, when a new ontology has been submitted, it should be documented in the 'Ontology Review Rotation' sheet in the same document.
```

2024-08-11 20:22 UTC, nlharris commented on docs/roles/RoleNORManager.md
> +The OBO Duty Rotation Table is a Google Doc available [here](https://docs.google.com/spreadsheets/d/19GrEWVnpxjnrig0iYUOiUvsZ0JDbprMh1USnRb-SXtg/edit).
```suggestion
The OBO Duty Rotation Table is a Google spreadsheet available [here](https://docs.google.com/spreadsheets/d/19GrEWVnpxjnrig0iYUOiUvsZ0JDbprMh1USnRb-SXtg/edit).
```

2024-08-11 21:24 UTC, nlharris requested changes
Changes look fine. I found another sentence that was confusing and suggested edits.

2024-08-11 21:24 UTC, nlharris commented on docs/roles/RoleNORManager.md
> +In addition, when a new ontology has been submitted, it should be documented in the 'Ontology Review Rotation' sheet in the same document.
```suggestion
In addition, when a new ontology has been submitted, it should be added to the ['Ontology Reviewers' tab](https://docs.google.com/spreadsheets/d/19GrEWVnpxjnrig0iYUOiUvsZ0JDbprMh1USnRb-SXtg/edit?gid=1683009411#gid=1683009411) in the OBO Duty Rotation spreadsheet.
```

2024-08-11 21:24 UTC, nlharris commented on docs/roles/RoleNORManager.md
> +In addition, when a new ontology has been submitted, it should be documented in the 'Ontology Review Rotation' sheet in the same document.
Sorry, I missed this in my first edit.

2024-08-12 13:57 UTC, pfabry commented
What was the problem with the previous PR ? Since it seemed to be on my side, I'd like to avoid repeating it.

2024-08-12 14:01 UTC, matentzn commented
> What was the problem with the previous PR ? Since it seemed to be on my side, I'd like to avoid repeating it.

I am not sure, but it _looked_ to me like you were using a windows computer to save the documentation, causing _all_ lines to appear in the diff. Check the diff (files changed) in you PR to see how much red and green there is!

2024-08-12 14:14 UTC, pfabry commented
> I am not sure, but it _looked_ to me like you were using a windows computer to save the documentation, causing _all_ lines to appear in the diff. Check the diff (files changed) in you PR to see how much red and green there is!

Indeed, I am using a Windows computer. If I'am converting the EOL characeter to Unix format, that should do the trick?

2024-08-12 14:17 UTC, matentzn commented
I would hope so, but I can't promise it :)

2024-08-19 00:32 UTC, nlharris commented
What's the next step here? Should Nico make the requested change?

2024-08-19 00:33 UTC, nlharris requested changes

2024-08-19 00:33 UTC, nlharris commented on docs/roles/RoleNORManager.md
> +When a new member is added to OBO Foundry, the OBO NOR reviewer should add their name to this table. Likewise, former members should be removed from the table. The list of current OBO Foundry members
```suggestion
When a new member is added to the OBO Operations Committee, the OBO NOR reviewer should add the new member's name to this table. Similarly, former members should be removed from the table. The list of current OBO Operations members is maintained in the file [operations.yml](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_data/operations.yml).
```

2024-08-19 14:50 UTC, nataled commented
FWIW, I agree with Nomi's proposed change.

2024-08-19 15:04 UTC, pfabry commented
> FWIW, I agree with Nomi's proposed change.

Me too.

2024-08-20 00:18 UTC, nlharris commented
I assume I'm not supposed to re-review this?

2024-08-20 05:46 UTC, matentzn commented
For QC purposes you have to approve!

2024-08-20 06:09 UTC, nlharris approved these changes

2024-08-20 06:18 UTC, merged